# Generated by Django 4.1.5 on 2023-02-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='oraganization',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='blog.category'),
        ),
    ]
