# Generated by Django 4.1.5 on 2023-02-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_oraganization_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraganization',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oraganization', to='blog.category'),
        ),
    ]
