# Generated by Django 4.1.5 on 2023-02-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_oraganization_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60)),
                ('picture', models.ImageField(upload_to='organization/icons/', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание организации')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='blog.category')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.DeleteModel(
            name='Oraganization',
        ),
    ]
