# Generated by Django 4.1.5 on 2023-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_organization_picture_organization_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='image',
        ),
        migrations.AddField(
            model_name='organization',
            name='picture',
            field=models.ImageField(null=True, upload_to='organization/icons/', verbose_name='Изображение'),
        ),
    ]
