# Generated by Django 4.1.5 on 2023-02-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_addmemory_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmemory',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
