# Generated by Django 4.1.5 on 2023-02-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_addmemory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mobile',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
    ]
