# Generated by Django 4.1.5 on 2023-02-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_organization_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='category',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ManyToManyField(null=True, related_name='organizations', to='blog.category'),
        ),
    ]
