# Generated by Django 4.1.5 on 2023-02-20 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_organization_category_organization_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.ManyToManyField(related_name='organizations', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='VoluenteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True, unique=True, verbose_name='Электронная почта')),
                ('mobile', models.IntegerField(verbose_name='Номер телефона')),
                ('answer1', models.TextField(verbose_name='Почему вы хотите стать именно нашим волонтером?')),
                ('answer2', models.IntegerField(verbose_name='Сколько часов в день можете уделять волонтерству? ')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_apllication', to='blog.organization')),
            ],
        ),
    ]
