# Generated by Django 4.1.5 on 2023-02-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_voluenteerapplication_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluenteerapplication',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluenteers', to='blog.organization'),
        ),
    ]
