# Generated by Django 4.1.5 on 2023-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_voluenteerapplication_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluenteerapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
