# Generated by Django 4.1.5 on 2023-02-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_organization_dop_dscr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='blog.organization')),
            ],
        ),
    ]
