# Generated by Django 4.1.5 on 2023-02-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
