# Generated by Django 4.1.5 on 2023-02-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_socialnetworks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
