# Generated by Django 4.1.5 on 2023-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_socialnetworks_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_netw',
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SocialNetworks',
        ),
    ]
