# Generated by Django 4.1.5 on 2023-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_social_netw_user_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('slug', models.SlugField(max_length=60)),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.AddField(
            model_name='user',
            name='social_netw',
            field=models.ManyToManyField(limit_choices_to=5, to='accounts.socialnetworks'),
        ),
    ]
