# Generated by Django 4.1.5 on 2023-02-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_socialnetworks_remove_user_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
